const bcrypt = require('bcryptjs');
const pool = require('../config/db');

async function getRoleId(role) { const [[row]] = await pool.query('SELECT id_role FROM roles WHERE nama_role=?', [role]); return row?.id_role; }
exports.getAll = async (_, res) => { const [rows] = await pool.query('SELECT u.id_user,u.id_role,u.nama,u.email,u.no_hp,u.alamat,u.status,u.created_at,r.nama_role FROM users u JOIN roles r ON u.id_role=r.id_role ORDER BY u.id_user DESC'); res.json(rows); };
exports.getById = async (req, res) => { const [rows] = await pool.query('SELECT u.id_user,u.id_role,u.nama,u.email,u.no_hp,u.alamat,u.status,r.nama_role FROM users u JOIN roles r ON u.id_role=r.id_role WHERE id_user=?', [req.params.id]); rows.length ? res.json(rows[0]) : res.status(404).json({ message: 'User tidak ditemukan.' }); };
exports.create = async (req, res) => { const { nama,email,password,no_hp,alamat,role='sales',status='aktif' } = req.body; if (!nama || !email || !password) return res.status(400).json({ message: 'Nama, email, dan password wajib diisi.' }); const idRole = await getRoleId(role); const hash = await bcrypt.hash(password, 10); const [r] = await pool.query('INSERT INTO users (id_role,nama,email,password,no_hp,alamat,status) VALUES (?,?,?,?,?,?,?)', [idRole,nama,email,hash,no_hp || '',alamat || '',status]); res.status(201).json({ message: 'User berhasil ditambahkan.', id_user: r.insertId }); };
exports.update = async (req, res) => { const { nama,email,password,no_hp,alamat,role='sales',status='aktif' } = req.body; const idRole = await getRoleId(role); if (password) { const hash = await bcrypt.hash(password,10); await pool.query('UPDATE users SET id_role=?,nama=?,email=?,password=?,no_hp=?,alamat=?,status=? WHERE id_user=?', [idRole,nama,email,hash,no_hp || '',alamat || '',status,req.params.id]); } else { await pool.query('UPDATE users SET id_role=?,nama=?,email=?,no_hp=?,alamat=?,status=? WHERE id_user=?', [idRole,nama,email,no_hp || '',alamat || '',status,req.params.id]); } res.json({ message: 'User berhasil diperbarui.' }); };
exports.remove = async (req, res) => { await pool.query('DELETE FROM users WHERE id_user=?', [req.params.id]); res.json({ message: 'User berhasil dihapus.' }); };
exports.updateStatus = async (req, res) => { await pool.query('UPDATE users SET status=? WHERE id_user=?', [req.body.status, req.params.id]); res.json({ message: 'Status user berhasil diperbarui.' }); };
