import { useEffect, useMemo, useState } from 'react';
import AppLayout from '../../components/AppLayout.jsx';
import { getProducts } from '../../services/productService.js';
import { getPackages } from '../../services/packageService.js';
import { createOrder } from '../../services/orderService.js';
import { getStoredUser, rupiah } from '../../utils/format.js';

function BuatPesanan() {
  const user = getStoredUser(); const [products, setProducts] = useState([]); const [packages, setPackages] = useState([]); const [items, setItems] = useState([]); const [catatan, setCatatan] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { getProducts({ status: 'aktif' }).then(res => setProducts(res.data)); getPackages().then(res => setPackages(res.data)); const stored = localStorage.getItem('selectedPackageForOrder'); if (stored) { const paket = JSON.parse(stored); setItems([{ type: 'paket', id_paket: paket.id_paket, nama: paket.nama_paket, harga: Number(paket.total_harga), jumlah: 1 }]); localStorage.removeItem('selectedPackageForOrder'); } }, []);
  const total = useMemo(() => items.reduce((s, i) => s + (Number(i.harga) * Number(i.jumlah || 1)), 0), [items]);
  const addProduct = (id) => { const p = products.find(x => String(x.id_produk) === String(id)); if (!p) return; setItems([...items, { type: 'produk', id_produk: p.id_produk, nama: p.nama_produk, harga: Number(p.harga), jumlah: 1 }]); };
  const addPackage = (id) => { const p = packages.find(x => String(x.id_paket) === String(id)); if (!p) return; setItems([...items, { type: 'paket', id_paket: p.id_paket, nama: p.nama_paket, harga: Number(p.total_harga), jumlah: 1 }]); };
  const submit = async () => { if (!items.length) return setMessage('Pilih minimal satu produk atau paket.'); const payload = { id_user: user.id_user, catatan, items: items.map(i => ({ id_produk: i.id_produk, id_paket: i.id_paket, jumlah: Number(i.jumlah), harga: Number(i.harga) })) }; const res = await createOrder(payload); setItems([]); setCatatan(''); setMessage(`Pesanan berhasil dibuat dengan nomor #${res.data.id_pesanan}`); };
  return <AppLayout role="sales" title="Buat Pesanan Cepat"><div className="grid-2"><div className="panel form-grid"><p className="page-kicker">Tambah Item</p><h2>Pilih Produk / Paket Bundling</h2><select onChange={(e) => { addProduct(e.target.value); e.target.value = ''; }}><option value="">Tambah produk satuan</option>{products.map(p => <option key={p.id_produk} value={p.id_produk}>{p.nama_produk} - {rupiah(p.harga)}</option>)}</select><select onChange={(e) => { addPackage(e.target.value); e.target.value = ''; }}><option value="">Tambah paket bundling</option>{packages.map(p => <option key={p.id_paket} value={p.id_paket}>{p.nama_paket} - {rupiah(p.total_harga)}</option>)}</select><textarea placeholder="Catatan pesanan" value={catatan} onChange={(e) => setCatatan(e.target.value)} /></div><div className="panel"><p className="page-kicker">Keranjang Pesanan</p><h2>Ringkasan</h2>{items.length === 0 ? <div className="empty-state">Belum ada item.</div> : items.map((item, idx) => <div className="cart-row" key={idx}><div><strong>{item.nama}</strong><span>{item.type}</span></div><input type="number" min="1" value={item.jumlah} onChange={(e) => setItems(items.map((it, i) => i === idx ? { ...it, jumlah: e.target.value } : it))} /><strong>{rupiah(item.harga * item.jumlah)}</strong><button className="btn btn-sm btn-danger" onClick={() => setItems(items.filter((_, i) => i !== idx))}>Hapus</button></div>)}<h2>Total: {rupiah(total)}</h2><button className="btn btn-primary full" onClick={submit}>Simpan Pesanan</button>{message && <div className="alert success">{message}</div>}</div></div></AppLayout>;
}
export default BuatPesanan;
